# Generated by Django 6.0.6 on 2026-06-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOP', 'STOP'), ('LIMIT', 'LIMIT')], max_length=16)),
                ('action', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('margin', models.FloatField()),
                ('price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('base_currency', models.CharField(max_length=16)),
                ('quote_currency', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RecursiveStraddleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('long_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_order', to='trading.executionorder')),
                ('short_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_order', to='trading.executionorder')),
            ],
        ),
    ]
