# Generated by Django 6.0.6 on 2026-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionorder',
            name='stop_loss',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='executionorder',
            name='take_profit',
            field=models.FloatField(default=None, null=True),
        ),
    ]
