# Generated by Django 6.0.6 on 2026-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursivestraddleorder',
            name='orders_placed',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='recursivestraddleorder',
            name='units_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
