# Generated by Django 6.0.6 on 2026-07-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_recursivestraddleorder_orders_placed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursivestraddleorder',
            name='max_units',
            field=models.FloatField(default=None, null=True),
        ),
    ]
