# Generated by Django 6.0.6 on 2026-07-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_recursivestraddleorder_max_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursivestraddleorder',
            name='initial_units_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
