# Generated by Django 6.0.6 on 2026-08-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_recursivestraddleorder_initial_units_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursivestraddleorder',
            name='max_orders',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
