# Generated by Django 6.0.6 on 2026-09-15 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trading', '0005_recursivestraddleorder_max_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursivestraddleorder',
            name='long_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_long_orders', to='trading.executionorder'),
        ),
        migrations.AlterField(
            model_name='recursivestraddleorder',
            name='short_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_short_orders', to='trading.executionorder'),
        ),
        migrations.CreateModel(
            name='RecursiveMarketMakingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('units_multiplier', models.FloatField(default=1.0)),
                ('max_units', models.FloatField(default=None, null=True)),
                ('max_orders', models.IntegerField(default=None, null=True)),
                ('orders_placed', models.IntegerField(default=0.0)),
                ('initial_units_corrected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('long_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_long_orders', to='trading.executionorder')),
                ('short_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_short_orders', to='trading.executionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
