# Generated by Django 6.0.6 on 2026-06-15 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=256)),
                ('token', models.TextField()),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
