# Generated by Django 6.0.6 on 2026-06-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='streaming_url',
        ),
    ]
